name: BentoML CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bentoml
          pip install -r requirements.txt --no-deps

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Download model files from S3
        run: |
          mkdir -p models
          aws s3 cp s3://anomaly-detection-pkl/scaler.pkl models/scaler.pkl
          aws s3 cp s3://anomaly-detection-pkl/anomaly_detection.pkl models/anomaly_detection.pkl

      - name: Save models to BentoML store
        working-directory: ./src
        run: |
          python save_model.py

      - name: Build BentoML Service
        working-directory: .
        run: |
          ls -la
          cat bentofile.yaml
          bentoml build

      - name: Test
        run: |
          echo "Unit testing is currently empty; will be added later"

      - name: Deploy to cloud service
        run: | 
          echo "Deployment step is currently empty; will be added later"
